In [1]:
import pandas as pd

In [2]:
# 1. Create a tiny dataset
data = {
    'Material': ['Iron', 'Alumina', 'Polyethylene'],
    'Class': ['Metal', 'Ceramic', 'Polymer'],
    'Melting_Temp_K': [1811, 2345, 400]
}

df = pd.DataFrame(data)

# 2. Unit Conversion: Kelvin to Celsius
# Formula: C = K - 273.15
df['Melting_Temp_C'] = df['Melting_Temp_K'] - 273.15

print("\n--- After Unit Conversion ---")
display(df)

# 3. Categorical Encoding (One-Hot Encoding)
# We turn the 'Class' text column into machine-readable binary columns
df_encoded = pd.get_dummies(df, columns=['Class'])

print("\n--- After Categorical Encoding ---")
display(df_encoded)

--- After Unit Conversion ---

       Material    Class  Melting_Temp_K  Melting_Temp_C
0          Iron    Metal            1811         1537.85
1       Alumina  Ceramic            2345         2071.85
2  Polyethylene  Polymer             400          126.85

--- After Categorical Encoding ---

,Material,Melting_Temp_K,Melting_Temp_C,Class_Ceramic,Class_Metal,Class_Polymer
0,Iron,1811,1537.85,False,True,False
1,Alumina,2345,2071.85,True,False,False
2,Polyethylene,400,126.85,False,False,True

In [3]:
import pandas as pd

In [12]:
git checkout main
git pull origin main

echo "This is the main version" > conflict_test.txt
git add conflict_test.txt
git commit -m "Added text to main"

git checkout -b experiment_branch

echo "This is the EXPERIMENT version" > conflict_test.txt
git add conflict_test.txt
git commit -m "Changed text in experiment"

git checkout main

echo "This is the UPDATED MAIN version" > conflict_test.txt
git add conflict_test.txt
git commit -m "Changed text in main again"

git merge experiment_branch

SyntaxError: invalid syntax (971607078.py, line 1)

In [14]:
!git init

!echo "start" > conflict_test.txt
!git add conflict_test.txt
!git commit -m "Initial commit"

!git branch -M main

!echo "This is the main version" > conflict_test.txt
!git add conflict_test.txt
!git commit -m "Added text to main"

!git checkout -b experiment_branch

!echo "This is the EXPERIMENT version" > conflict_test.txt
!git add conflict_test.txt
!git commit -m "Changed text in experiment"

!git checkout main

!echo "This is the UPDATED MAIN version" > conflict_test.txt
!git add conflict_test.txt
!git commit -m "Changed text in main again"

!git merge experiment_branch

Reinitialized existing Git repository in C:/Users/Lenovo/anaconda_projects/52a4d4d3-39a2-43f3-ac14-c91f365e8075/.git/
[main 9998c33] Initial commit
[main 6e65e6e] Added text to main
 1 file changed, 1 insertion(+), 1 deletion(-)

fatal: a branch named 'experiment_branch' already exists

[main 793efc1] Changed text in experiment
 1 file changed, 1 insertion(+), 1 deletion(-)

Already on 'main'

[main 4f5b09b] Changed text in main again
 1 file changed, 1 insertion(+), 1 deletion(-)
Already up to date.